require("core.plugin_config.lsp")
require("core.plugin_config.harpoon")
require("core.plugin_config.treesitter")
require("core.plugin_config.undotree")
require("core.plugin_config.refactoring")
require("core.plugin_config.fugitive")
require("core.plugin_config.lualine")
